# Project information
site_name: Citrix ADC Istio Adaptor
site_title: Developer Docs
site_description: Documentation for the Citrix ADC integration with Istio
site_url: https://developer-docs.citrix.com

# Repository
repo_name: "Citrix Istio Adaptor"
repo_url: "https://github.com/citrix/citrix-istio-adaptor"
edit_uri: "edit/master/docs"

# Copyright
copyright: 'Copyright &copy; 1999-2019 Citrix Systems, Inc. All rights reserved. '

extra_css:
  - 'assets/stylesheets/extra.css'

# Configuration
theme:
  name: null
  custom_dir: devdocs-theme

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: false
  palette:
    primary: white
    accent: blue
  font: false
  favicon: /media/favicon.ico
  logo: https://developer-docs.citrix.com/_static/Citrix_Logo_Black.png

# Customization
extra:
  social:
    - type: youtube
      link: https://www.youtube.com/channel/UCiOupk9QF6jdk3EDKTHDykA
    - type: github-alt
      link: https://github.com/citrix
    - type: twitter
      link: https://twitter.com/citrixdeveloper
    - type: linkedin
      link: https://www.linkedin.com/company/citrix/

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - meta
  - extra

# Page tree
nav:
- Overview: index.md
- Release notes: https://github.com/citrix/citrix-istio-adaptor/releases
- Deployment topologies: istio-integration/architecture.md
- Deploy the Citrix istio adaptor:
  - Using Helm chart: istio-integration/deploy-istio-adaptor-helm-chart.md
- Licensing: cpx-licensing.md
- Developer Guide: developer-guide.md
- Questions?: https://discussions.citrix.com/forum/1385-citrix-developer-exchange/